import { GatewayError } from "@/domain/errors";
import { getScenario, updateScenario, updateViewerProfile } from "@/infrastructure/scenario/repository";
import type { OpenRequest, Order, QuickDealOffer, RequestDraft, ServiceListing, ViewerAccount, WorkPlan } from "@/types/domain";
const wait = (ms = 120) => new Promise((resolve) => window.setTimeout(resolve, ms));
const event = (type: string, aggregateType: string, aggregateId: string, note: string, actorId = "USR-ROSA-01") => ({ id: `EV-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, type, aggregateType, aggregateId, actorId, at: new Date().toISOString(), note });
export async function getViewer(): Promise<ViewerAccount> { await wait(80); return getScenario().viewer; }
export async function updateProfile(input: { name: string; area: string }): Promise<ViewerAccount> { await wait(160); return updateViewerProfile(input).viewer; }
export async function getHome() { await wait(); const state = getScenario(); return { viewer: state.viewer, services: state.services, requests: state.requests, order: state.order, plan: state.plan }; }
export async function listServices(): Promise<ServiceListing[]> { await wait(120); return getScenario().services; }
export async function getListing(id: string): Promise<ServiceListing> { await wait(100); const listing = getScenario().services.find((item) => item.id === id); if (!listing) throw new GatewayError("not_found", "Listing is unavailable", { id }); return listing; }
export async function listRequests(): Promise<OpenRequest[]> { await wait(120); return getScenario().requests; }
export async function getOrder(id = "ORD-260801-08"): Promise<Order> { await wait(100); const order = getScenario().order; if (order.id !== id) throw new GatewayError("not_found", "Order is unavailable", { id }); return order; }
export async function getWorkPlan(): Promise<WorkPlan> { await wait(100); return getScenario().plan; }
export async function getQuickDeal(id = "QD-DEMO-01"): Promise<QuickDealOffer> { await wait(80); const deal = getScenario().quickDeal; if (deal.id !== id) throw new GatewayError("not_found", "Quick Deal is unavailable", { id }); return deal; }
export async function createRequest(input: RequestDraft): Promise<OpenRequest> { await wait(260); const state = getScenario(); const created: OpenRequest = { id: `REQ-DEMO-${state.requests.length + 1}`, title: input.title, buyer: { id: state.viewer.id, name: state.viewer.name, shortName: state.viewer.shortName, avatar: state.viewer.avatar, area: state.viewer.area }, area: input.area, budget: input.budget, category: input.category, proposals: 0, postedLabel: "just now", description: input.details, status: "open" }; updateScenario((draft) => { draft.requests = [created, ...draft.requests]; return event("request.created", "Request", created.id, "A fictional request was posted in this browser.", draft.reviewerActorId); }); return created; }
export async function quickDealStartCamera(): Promise<QuickDealOffer> { await wait(180); return updateScenario((draft) => { draft.quickDeal = { ...draft.quickDeal, status: "scanning" }; return event("quick_deal.scanning_started", "QuickDeal", draft.quickDeal.id, "Camera/QR transport is simulated; no money moved.", draft.reviewerActorId); }).quickDeal; }
export async function quickDealAdjust(delta: number): Promise<QuickDealOffer> { await wait(70); return updateScenario((draft) => { draft.quickDeal = { ...draft.quickDeal, amount: Math.max(10, draft.quickDeal.amount + delta), status: "offer_received" }; return event("quick_deal.amount_changed", "QuickDeal", draft.quickDeal.id, `Amount changed to ₱${draft.quickDeal.amount}.`, draft.reviewerActorId); }).quickDeal; }
export async function quickDealSendCounter(): Promise<QuickDealOffer> { await wait(180); return updateScenario((draft) => { draft.quickDeal = { ...draft.quickDeal, status: "counter_streaming", round: draft.quickDeal.round + 1 }; return event("quick_deal.counter_sent", "QuickDeal", draft.quickDeal.id, "Counter-offer is simulated in the shared review fixture.", draft.reviewerActorId); }).quickDeal; }
export async function quickDealAccept(): Promise<QuickDealOffer> { await wait(200); return updateScenario((draft) => { draft.quickDeal = { ...draft.quickDeal, status: "dual_confirm" }; return event("quick_deal.accepted", "QuickDeal", draft.quickDeal.id, "Offer accepted by the current simulated perspective.", draft.reviewerActorId); }).quickDeal; }
export async function quickDealConfirm(): Promise<QuickDealOffer> { await wait(200); return updateScenario((draft) => { draft.quickDeal = { ...draft.quickDeal, status: "waiting_sync", receiptId: "QD-260801-019" }; return event("quick_deal.confirmation_recorded", "QuickDeal", draft.quickDeal.id, "Confirmation recorded; this is not payment or settlement.", draft.reviewerActorId); }).quickDeal; }
export async function quickDealSync(): Promise<QuickDealOffer> { await wait(300); return updateScenario((draft) => { draft.quickDeal = { ...draft.quickDeal, status: "synced" }; return event("quick_deal.sync_simulated", "QuickDeal", draft.quickDeal.id, "A fictional sync completed; a durable backend is not connected.", draft.reviewerActorId); }).quickDeal; }
export async function quickDealTickFrame(): Promise<QuickDealOffer> { return updateScenario((draft) => { draft.quickDeal = { ...draft.quickDeal, frame: draft.quickDeal.frame === 6 ? 1 : draft.quickDeal.frame + 1 }; return undefined; }).quickDeal; }
export async function addPlanItem(title: string, amount: number): Promise<WorkPlan> { await wait(200); return updateScenario((draft) => { const id = `P${draft.plan.items.length + 1}`; draft.plan = { ...draft.plan, items: [...draft.plan.items, { id, title, amount, state: "needs_provider", paymentNote: "No provider chosen yet" }] }; return event("work_plan.item_added", "WorkPlan", draft.plan.id, `Added planning item ${title}.`, draft.reviewerActorId); }).plan; }
export async function advanceWork(): Promise<Order> { await wait(220); return updateScenario((draft) => { if (draft.reviewerActorId !== draft.order.provider.id) throw new GatewayError("permission", "Only the Provider can send work for review."); draft.order = { ...draft.order, workStatus: "awaiting_buyer_review", nextActor: "buyer", nextAction: "Review Maya's first drawing", steps: draft.order.steps.map((step, index) => index === 1 ? { ...step, state: "done", evidence: "first-drawing.jpg", note: "First drawing sent" } : index === 2 ? { ...step, state: "active" } : step) }; return event("work.review_requested", "Order", draft.order.id, "Provider requested Buyer review; evidence is not automatic verification.", draft.reviewerActorId); }).order; }
export async function approveWork(): Promise<Order> { await wait(180); return updateScenario((draft) => { if (draft.reviewerActorId !== draft.order.buyer.id) throw new GatewayError("permission", "Only the Buyer can approve this work."); if (draft.order.workStatus !== "awaiting_buyer_review") throw new GatewayError("invariant", "Work is not waiting for Buyer review."); draft.order = { ...draft.order, workStatus: "completed", orderStatus: "review", nextActor: "buyer", nextAction: "Confirm the cash report or raise a concern", steps: draft.order.steps.map((step) => step.id === "S3" ? { ...step, state: "done", note: "Buyer approved the submitted work." } : step) }; return event("work.approved", "Order", draft.order.id, "Buyer approved Work. Payment remains an independent state machine.", draft.reviewerActorId); }).order; }
export async function openWorkConcern(): Promise<Order> { await wait(150); return updateScenario((draft) => { if (draft.reviewerActorId !== draft.order.buyer.id) throw new GatewayError("permission", "Only the Buyer can open this concern."); draft.order = { ...draft.order, workStatus: "concern_open", orderStatus: "review", nextActor: "provider", nextAction: "Provider should respond to the concern" }; return event("work.concern_opened", "Order", draft.order.id, "Buyer opened a concern; no payment was settled automatically.", draft.reviewerActorId); }).order; }
export async function reportExternalCash(): Promise<Order> { await wait(150); return updateScenario((draft) => { const actor = draft.reviewerActorId; const isBuyer = actor === draft.order.buyer.id; const isProvider = actor === draft.order.provider.id; if (!isBuyer && !isProvider) throw new GatewayError("permission", "Only a transaction participant can report cash."); draft.order = { ...draft.order, buyerCashReported: isBuyer ? true : draft.order.buyerCashReported, providerCashReported: isProvider ? true : draft.order.providerCashReported, cashStatus: isBuyer && draft.order.providerCashReported ? "mutually_acknowledged" : isProvider && draft.order.buyerCashReported ? "mutually_acknowledged" : isBuyer ? "buyer_reported" : "provider_reported" }; return event("payment.external_cash_reported", "Order", draft.order.id, `${isBuyer ? "Buyer" : "Provider"} reported cash directly. This is an attestation, not platform custody.`, actor); }).order; }
