import { BriefcaseBusiness, Compass, Home, Menu, Plus, ScanLine, UserRound, X } from "lucide-react";
import type { ReactNode } from "react";
import { Button } from "@/components/ui";
import { useApp } from "@/context/AppContext";
import { useRouter } from "@/context/RouterContext";
import { cn } from "@/lib/cn";

const navigation = [{ to: "/", label: "Home", icon: Home }, { to: "/explore", label: "Browse", icon: Compass }, { to: "/quick-deal", label: "Quick Deal", icon: ScanLine }, { to: "/activity", label: "Activity", icon: BriefcaseBusiness }, { to: "/me", label: "Me", icon: UserRound }];
function NavContent() { const { route } = useRouter(); const { openComposer } = useApp(); return <><a href="#/" className="flex items-center gap-3 px-2"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-forest-600 font-display font-extrabold text-white">S</span><span><strong className="block font-display text-lg text-ink-950">Serbizyu</strong><small className="text-[10px] font-bold uppercase tracking-wider text-forest-600">Tagudin</small></span></a><Button className="mt-7 w-full" size="lg" leftIcon={<Plus className="h-4 w-4" />} onClick={openComposer}>I need help</Button><a href="#/me" className="mt-3 flex min-h-12 items-center justify-center rounded-xl border border-ink-100 bg-white text-sm font-bold text-ink-700">I offer something</a><nav className="mt-7 space-y-1">{navigation.map(({ to, label, icon: Icon }) => <a key={to} href={`#${to}`} className={cn("nav-item", route === to && "nav-item-active")}><Icon className="h-[18px] w-[18px]" />{label}</a>)}</nav><div className="mt-auto rounded-2xl bg-ink-950 p-4 text-xs text-white"><strong>Rosa’s account</strong><p className="mt-1 text-white/60">Requests · listings · helps Lola Nena</p></div></>; }
export function AppShell({ children }: { children: ReactNode }) { const { sidebarOpen, setSidebarOpen } = useApp(); return <div className="min-h-screen"><aside className="fixed inset-y-0 left-0 z-40 hidden w-[252px] flex-col border-r border-ink-100 bg-cream-100 p-4 lg:flex"><NavContent /></aside>{sidebarOpen && <button className="fixed inset-0 z-40 bg-ink-950/40 lg:hidden" onClick={() => setSidebarOpen(false)} aria-label="Close navigation" />}<aside className={cn("fixed inset-y-0 left-0 z-50 flex w-[284px] flex-col bg-cream-100 p-4 shadow-2xl transition-transform lg:hidden", sidebarOpen ? "translate-x-0" : "-translate-x-full")}><button className="absolute right-3 top-3" onClick={() => setSidebarOpen(false)}><X /></button><NavContent /></aside><div className="app-canvas"><header className="sticky top-0 z-30 border-b border-ink-100 bg-cream-100/90 backdrop-blur"><div className="mx-auto flex h-[64px] max-w-[1480px] items-center px-4 sm:px-6 lg:px-8"><button className="mr-3 lg:hidden" onClick={() => setSidebarOpen(true)}><Menu /></button><p className="font-display font-bold text-ink-950">Tagudin today</p><span className="ml-auto text-xs font-bold text-forest-700">● Online</span></div></header>{children}</div><nav className="fixed inset-x-3 bottom-3 z-40 grid grid-cols-5 rounded-2xl border border-ink-100 bg-white p-1.5 shadow-2xl lg:hidden">{navigation.map(({ to, label, icon: Icon }) => <a key={to} href={`#${to}`} className="flex min-h-12 flex-col items-center justify-center gap-1 text-[9px] font-bold text-ink-500"><Icon className="h-[18px] w-[18px]" />{label}</a>)}</nav></div>; }
