import { AlertTriangle, ArrowRight, Check, CheckCircle2, Circle, Clock3, FileImage, Flag, LockKeyhole, MessageCircle, MoreHorizontal, Paperclip, Send, Sparkles } from "lucide-react";
import { useState } from "react";
import { useAdvanceWork, useOrder } from "@/api/hooks";
import { Avatar, Badge, Button, Card, CardContent, CardHeader, CardTitle } from "@/components/ui";
import { useApp } from "@/context/AppContext";
import { cn, formatPeso } from "@/lib/cn";
import type { WorkStep } from "@/types/domain";

export function DealRoomPage() {
  const { role } = useApp();
  const orderQuery = useOrder();
  const advanceWork = useAdvanceWork();
  const [tab, setTab] = useState<"work" | "messages" | "timeline">("work");
  const order = orderQuery.data;

  if (!order) return <main className="page-wrap"><div className="h-[640px] animate-pulse rounded-3xl bg-white" /></main>;

  const roleAction = role === "provider"
    ? { label: order.workStatus === "awaiting_buyer_review" ? "Waiting for Buyer review" : "Upload first draft", disabled: order.workStatus === "awaiting_buyer_review", action: () => advanceWork.mutate() }
    : role === "buyer"
      ? { label: order.workStatus === "awaiting_buyer_review" ? "Review first draft" : "Follow Work progress", disabled: order.workStatus !== "awaiting_buyer_review", action: () => setTab("work") }
      : { label: "Inspect audit context", disabled: false, action: () => setTab("timeline") };

  return (
    <main className="page-wrap">
      <div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge tone="forest"><span className="h-1.5 w-1.5 rounded-full bg-forest-500" /> Active deal</Badge><Badge tone="neutral">{order.id}</Badge><Badge tone="blue">A9 Digital delivery</Badge></div><h1 className="mt-3 font-display text-3xl font-extrabold tracking-[-.045em] text-ink-950">{order.title}</h1><p className="mt-1 text-sm text-ink-500">A shared workspace for terms, Work, payment, messages, and recovery.</p></div><div className="flex gap-2"><Button variant="outline" leftIcon={<Flag className="h-4 w-4" />}>Raise concern</Button><Button loading={advanceWork.isPending} disabled={roleAction.disabled} leftIcon={<ArrowRight className="h-4 w-4" />} onClick={roleAction.action}>{roleAction.label}</Button></div></div>

      <section className="grid gap-5 2xl:grid-cols-[minmax(0,1fr)_390px]">
        <div className="min-w-0 space-y-5">
          <Card className="overflow-hidden">
            <div className="hero-mesh soft-noise relative p-6 text-white sm:p-7"><div className="relative z-10 flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-white/50">Next responsible actor</p><div className="mt-3 flex items-center gap-3"><Avatar initials={order.nextActor === "buyer" ? order.buyer.avatar : order.provider.avatar} tone={order.nextActor === "buyer" ? "mango" : "forest"} className="h-12 w-12" /><div><h2 className="font-display text-xl font-extrabold">{order.nextAction}</h2><p className="mt-1 text-xs text-white/60">{order.nextActor === "buyer" ? order.buyer.name : order.provider.name} · Work responsibility</p></div></div></div><div className="grid grid-cols-3 gap-2"><HeroStatus label="Order" value="Accepted" icon={CheckCircle2} /><HeroStatus label="Work" value={order.workStatus === "awaiting_buyer_review" ? "For review" : "In progress"} icon={Sparkles} /><HeroStatus label="Payment" value={cashLabel(order.cashStatus)} icon={Circle} /></div></div></div>
            <div className="flex overflow-x-auto border-b border-ink-100 px-3 sm:px-5">{(["work", "messages", "timeline"] as const).map((item) => <button key={item} className={cn("min-h-12 shrink-0 border-b-2 px-4 text-xs font-extrabold capitalize transition", tab === item ? "border-forest-600 text-forest-700" : "border-transparent text-ink-400 hover:text-ink-800")} onClick={() => setTab(item)}>{item === "work" ? "Work & evidence" : item}</button>)}</div>
            <div className="p-5 sm:p-7">{tab === "work" ? <WorkPanel steps={order.steps} role={role} /> : tab === "messages" ? <MessagesPanel role={role} /> : <TimelinePanel events={order.timeline} />}</div>
          </Card>

          <Card><CardHeader><div><p className="eyebrow">Terms snapshot v1</p><CardTitle className="mt-1">What both sides accepted</CardTitle></div><Badge tone="forest"><LockKeyhole className="h-3 w-3" /> Preserved</Badge></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Term label="Scope" value="Invitation layout + 1 revision" /><Term label="Amount" value={formatPeso(order.amount)} /><Term label="Work shape" value="A9 Digital delivery" /><Term label="Payment" value="External Cash" /></div><p className="mt-4 rounded-xl bg-cream-100 px-4 py-3 text-xs leading-5 text-ink-500"><strong className="text-ink-800">Change rule:</strong> corrections create linked history. The original terms are never silently overwritten.</p></CardContent></Card>
        </div>

        <aside className="space-y-5">
          <Card className="overflow-hidden"><CardHeader><div><p className="eyebrow">Separate states</p><CardTitle className="mt-1">Three facts, not one “paid” badge</CardTitle></div></CardHeader><CardContent className="space-y-3"><StateRow tone="forest" label="Order" state="Accepted" meaning="Both sides confirmed snapshot v1." /><StateRow tone="mango" label="Work" state={order.workStatus === "awaiting_buyer_review" ? "Awaiting Buyer review" : "In progress"} meaning="Maya owns the current Work step." /><StateRow tone="blue" label="Payment obligation" state={cashLabel(order.cashStatus)} meaning={order.cashStatus === "not_reported" ? "No cash report from either side." : "Declarations only; Work is unchanged."} /><div className="rounded-2xl border border-mango-100 bg-mango-50 p-4"><div className="flex gap-3"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-mango-600" /><p className="text-xs leading-5 text-mango-700"><strong>Serbizyu holds ₱0.</strong> External Cash goes directly between Buyer and Provider.</p></div></div><Button className="w-full" variant="outline" onClick={() => window.location.hash = "#/payments"}>Open payment details</Button></CardContent></Card>

          <Card><CardHeader><div><p className="eyebrow">People</p><CardTitle className="mt-1">Shared context, different actions</CardTitle></div><button className="text-ink-400"><MoreHorizontal className="h-5 w-5" /></button></CardHeader><CardContent className="space-y-4"><Person avatar={order.buyer.avatar} name={order.buyer.name} role="Buyer · confirms Work" tone="mango" /><Person avatar={order.provider.avatar} name={order.provider.name} role="Provider · performs Work" tone="forest" /><Button className="w-full" variant="ghost" leftIcon={<MessageCircle className="h-4 w-4" />} onClick={() => setTab("messages")}>Open conversation</Button></CardContent></Card>
        </aside>
      </section>
    </main>
  );
}

function WorkPanel({ steps, role }: { steps: WorkStep[]; role: "buyer" | "provider" | "admin" }) {
  return <div><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">A9 digital delivery</p><h2 className="mt-1 font-display text-xl font-extrabold text-ink-950">Meaningful Work steps</h2><p className="mt-1 text-xs text-ink-500">Each step has an owner, evidence expectation, and recovery route.</p></div><Badge tone="neutral">2 of 4 active</Badge></div><div className="step-rail mt-6">{steps.map((step) => <div key={step.id} className="relative z-10 flex gap-4 pb-6 last:pb-0"><span className={cn("grid h-9 w-9 shrink-0 place-items-center rounded-xl border-4 border-white shadow-sm", step.state === "done" ? "bg-forest-600 text-white" : step.state === "active" ? "bg-mango-300 text-ink-950" : "bg-ink-100 text-ink-400")}>{step.state === "done" ? <Check className="h-4 w-4" /> : step.state === "active" ? <Clock3 className="h-4 w-4" /> : <Circle className="h-3 w-3" />}</span><div className={cn("min-w-0 flex-1 rounded-2xl border p-4", step.state === "active" ? "border-mango-200 bg-mango-50" : "border-ink-100 bg-white")}><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-extrabold text-ink-900">{step.title}</h3><Badge tone={step.owner === "provider" ? "forest" : "mango"}>{step.owner} owns this</Badge></div><p className="mt-2 text-xs leading-5 text-ink-500">{step.note}</p>{step.evidence && <div className="mt-3 flex items-center gap-3 rounded-xl border border-ink-100 bg-cream-50 p-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-blue-600"><FileImage className="h-4 w-4" /></span><div><p className="text-xs font-bold text-ink-800">{step.evidence}</p><p className="text-[10px] text-ink-400">Evidence v1 · does not complete Work</p></div></div>}{step.state === "active" && role === step.owner && <Button className="mt-3" size="sm">{role === "provider" ? "Add evidence" : "Review evidence"}</Button>}</div></div>)}</div></div>;
}

function MessagesPanel({ role }: { role: string }) {
  return <div><div className="flex items-center justify-between"><div><p className="eyebrow">Order-linked conversation</p><h2 className="mt-1 font-display text-xl font-extrabold text-ink-950">Rosa ↔ Maya</h2></div><Badge tone="forest">Terms snapshot linked</Badge></div><div className="mt-6 space-y-4"><Message align="left" name="Maya" time="2:18 PM">I finished the first sketch. I’ll upload the clean draft next.</Message><Message align="right" name="Rosa" time="2:21 PM">Salamat. Please make the date easy to read.</Message><Message align="left" name="Maya" time="2:24 PM">Noted. That stays within the included revision.</Message></div><div className="mt-6 flex items-end gap-2 rounded-2xl border border-ink-100 bg-cream-50 p-2"><button className="grid h-10 w-10 place-items-center rounded-xl text-ink-400 hover:bg-white"><Paperclip className="h-4 w-4" /></button><textarea className="min-h-10 flex-1 resize-none bg-transparent px-2 py-2 text-sm outline-none" rows={1} placeholder={`Message as ${role}…`} /><Button size="icon" aria-label="Send message"><Send className="h-4 w-4" /></Button></div></div>;
}

function TimelinePanel({ events }: { events: { id: string; title: string; actor: string; at: string; note: string; tone?: string }[] }) {
  return <div><p className="eyebrow">Attributable history</p><h2 className="mt-1 font-display text-xl font-extrabold text-ink-950">What happened, without rewriting it</h2><div className="mt-6 space-y-1">{events.map((event) => <div key={event.id} className="grid grid-cols-[22px_1fr_auto] gap-3 border-b border-ink-100 py-4 last:border-0"><span className={cn("mt-1 h-3 w-3 rounded-full ring-4", event.tone === "good" ? "bg-forest-500 ring-forest-100" : event.tone === "warn" ? "bg-mango-400 ring-mango-100" : event.tone === "danger" ? "bg-coral-400 ring-coral-100" : "bg-ink-300 ring-ink-100")} /><div><p className="text-sm font-extrabold text-ink-900">{event.title}</p><p className="mt-1 text-xs leading-5 text-ink-500">{event.note}</p><p className="mt-1 text-[10px] font-bold text-ink-400">by {event.actor}</p></div><span className="text-[10px] font-bold text-ink-400">{event.at}</span></div>)}</div></div>;
}

function HeroStatus({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Circle }) { return <div className="min-w-[88px] rounded-2xl border border-white/15 bg-white/10 p-3"><Icon className="h-4 w-4 text-mango-300" /><span className="mt-3 block text-[9px] font-bold uppercase tracking-wider text-white/45">{label}</span><strong className="mt-1 block text-[11px] capitalize text-white">{value}</strong></div>; }
function StateRow({ tone, label, state, meaning }: { tone: "forest" | "mango" | "blue"; label: string; state: string; meaning: string }) { const styles = { forest: "bg-forest-50 border-forest-100 text-forest-800", mango: "bg-mango-50 border-mango-100 text-mango-700", blue: "bg-blue-50 border-blue-100 text-blue-700" }; return <div className={cn("rounded-2xl border p-4", styles[tone])}><p className="text-[9px] font-extrabold uppercase tracking-[.14em] opacity-60">{label}</p><strong className="mt-1 block text-sm capitalize">{state}</strong><p className="mt-1 text-[11px] leading-4 opacity-75">{meaning}</p></div>; }
function Person({ avatar, name, role, tone }: { avatar: string; name: string; role: string; tone: "forest" | "mango" }) { return <div className="flex items-center gap-3"><Avatar initials={avatar} tone={tone} /><div><p className="text-sm font-extrabold text-ink-900">{name}</p><p className="text-[11px] text-ink-400">{role}</p></div></div>; }
function Message({ align, name, time, children }: { align: "left" | "right"; name: string; time: string; children: string }) { return <div className={cn("flex", align === "right" && "justify-end")}><div className={cn("max-w-[78%] rounded-2xl px-4 py-3", align === "right" ? "rounded-br-md bg-forest-600 text-white" : "rounded-bl-md bg-ink-100 text-ink-800")}><p className="text-xs leading-5">{children}</p><p className={cn("mt-1 text-[9px] font-bold", align === "right" ? "text-white/50" : "text-ink-400")}>{name} · {time}</p></div></div>; }
function Term({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-ink-100 bg-cream-50 p-3"><span className="text-[9px] font-extrabold uppercase tracking-[.12em] text-ink-400">{label}</span><strong className="mt-1 block text-xs text-ink-800">{value}</strong></div>; }
function cashLabel(status: string) { return status === "not_reported" ? "No report" : status.replaceAll("_", " "); }
