import { AlertTriangle, ArrowRight, BadgeCheck, Banknote, Check, ChevronRight, Copy, FileCheck2, FlaskConical, HandCoins, LoaderCircle, LockKeyhole, QrCode, Radio, RefreshCcw, ScanLine, ShieldCheck, Sparkles, WifiOff } from "lucide-react";
import { useMemo, useState } from "react";
import { Avatar, Badge, Button, Card, SectionHeading } from "@/components/ui";
import { cn } from "@/lib/cn";

const archetypes = [
  { id: "A1", title: "Linear project", description: "Named steps toward one outcome", icon: ArrowRight, compatible: ["cash", "proof", "direct", "tiwala"] },
  { id: "A3", title: "Appointment", description: "Time, place, arrival, no-show", icon: BadgeCheck, compatible: ["cash", "proof"] },
  { id: "A4", title: "Product handoff", description: "Capacity, condition, receipt", icon: HandCoins, compatible: ["cash", "proof"] },
  { id: "A9", title: "Digital delivery", description: "Version, revision, acceptance", icon: FileCheck2, compatible: ["cash", "proof", "direct", "tiwala"] },
];
const lanes = [
  { id: "cash", title: "External Cash", label: "Pilot-facing", sandbox: false },
  { id: "proof", title: "External Digital Proof", label: "Pilot-facing", sandbox: false },
  { id: "direct", title: "Direct Digital", label: "Sandbox only", sandbox: true },
  { id: "tiwala", title: "Tiwala Protected", label: "Sandbox only", sandbox: true },
];

export function PatternsPage() {
  const [frame, setFrame] = useState(1);
  const [shape, setShape] = useState("A1");
  const [lane, setLane] = useState("cash");
  const [offline, setOffline] = useState(false);
  const currentShape = archetypes.find((item) => item.id === shape) ?? archetypes[0];
  const compatible = currentShape.compatible.includes(lane);
  const snapshot = useMemo(() => ({ work_shape: shape, payment_lane: lane === "cash" ? "external_cash" : lane === "proof" ? "external_digital_proof" : `${lane}_sandbox`, order: "draft", guards: compatible ? "compatible" : "blocked" }), [compatible, lane, shape]);

  return (
    <main className="page-wrap">
      <section className="relative overflow-hidden rounded-3xl bg-ink-950 p-6 text-white shadow-lift sm:p-8 lg:p-10"><div className="absolute inset-y-0 right-0 w-1/2 pattern-grid opacity-20 [mask-image:linear-gradient(to_left,black,transparent)]" /><div className="relative max-w-3xl"><Badge tone="dark" className="bg-forest-500/20 text-forest-200 ring-forest-400/20"><Sparkles className="h-3 w-3" /> High-fidelity foundation</Badge><h1 className="mt-5 font-display text-4xl font-extrabold leading-[1.04] tracking-[-.055em] sm:text-5xl">The visual system — in product context.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-white/55">Not a generic button catalog. These foundations and patterns solve Serbizyu-specific trust, access, state, payment, evidence, and recovery problems.</p><div className="mt-6 flex flex-wrap gap-2"><Badge tone="dark" className="bg-white/10 ring-white/10">Responsive</Badge><Badge tone="dark" className="bg-white/10 ring-white/10">Icon + text</Badge><Badge tone="dark" className="bg-white/10 ring-white/10">44px targets</Badge><Badge tone="dark" className="bg-white/10 ring-white/10">Plain-language states</Badge></div></div></section>

      <section className="mt-8"><SectionHeading eyebrow="01 · Foundations" title="Warm, practical, and trustworthy" /><div className="grid gap-4 xl:grid-cols-[1.05fr_.95fr]">
        <Card className="p-5 sm:p-6"><p className="eyebrow">Color roles</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5"><ColorSwatch color="bg-ink-950" name="Deep ink" role="Structure" hex="#14211D" /><ColorSwatch color="bg-forest-600" name="Forest" role="Primary action" hex="#0D715F" /><ColorSwatch color="bg-mango-300" name="Mango" role="Attention" hex="#F9C64B" /><ColorSwatch color="bg-coral-400" name="Coral" role="Concern" hex="#ED6E4E" /><ColorSwatch color="bg-cream-100" name="Cream" role="Canvas" hex="#F8F5ED" dark /></div></Card>
        <Card className="p-5 sm:p-6"><p className="eyebrow">Type scale</p><div className="mt-5 space-y-4"><p className="font-display text-3xl font-extrabold tracking-[-.045em] text-ink-950">Local work, made clear.</p><p className="font-display text-xl font-bold tracking-[-.025em] text-ink-950">Decisions need hierarchy.</p><p className="max-w-lg text-sm leading-6 text-ink-500">Inter handles dense practical information. Plus Jakarta Sans gives decisions and sections a confident, human voice.</p><p className="font-mono text-[11px] font-bold uppercase tracking-[.14em] text-forest-600">PAY-OBLIGATION · BUYER_REPORTED</p></div></Card>
      </div></section>

      <section className="mt-10"><SectionHeading eyebrow="02 · Primitives" title="Small parts with real states" /><Card className="p-5 sm:p-6"><div className="grid gap-7 lg:grid-cols-3"><div><p className="text-xs font-extrabold text-ink-800">Actions</p><div className="mt-3 flex flex-wrap gap-2"><Button>Primary action</Button><Button variant="warm">Warm action</Button><Button variant="outline">Secondary</Button><Button variant="danger">Concern</Button><Button loading>Saving</Button></div></div><div><p className="text-xs font-extrabold text-ink-800">Status and scope</p><div className="mt-3 flex flex-wrap gap-2"><Badge tone="forest"><Check className="h-3 w-3" /> Completed</Badge><Badge tone="mango"><RefreshCcw className="h-3 w-3" /> Awaiting response</Badge><Badge tone="coral"><AlertTriangle className="h-3 w-3" /> Mismatch</Badge><Badge tone="sandbox"><FlaskConical className="h-3 w-3" /> Sandbox only</Badge><Badge tone="neutral">Policy TBD</Badge></div></div><div><p className="text-xs font-extrabold text-ink-800">Identity and actor</p><div className="mt-3 space-y-3"><div className="flex items-center gap-3"><Avatar initials="RM" tone="mango" /><div><p className="text-sm font-extrabold text-ink-900">Rosa Mendoza</p><p className="text-[11px] text-ink-400">Buyer · owns next review</p></div></div><div className="flex items-center gap-3"><Avatar initials="MD" tone="forest" /><div><p className="text-sm font-extrabold text-ink-900">Maya Dela Cruz</p><p className="text-[11px] text-ink-400">Provider · owns active Work</p></div></div></div></div></div></Card></section>

      <section className="mt-10"><SectionHeading eyebrow="03 · State language" title="Never rely on color or a code alone" /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StateCard icon={LoaderCircle} title="Processing evidence" meaning="The file arrived; no decision yet." next="Wait or safely retry" tone="blue" /><StateCard icon={WifiOff} title="Offline — draft kept" meaning="Nothing irreversible was sent." next="Retry when connected" tone="neutral" /><StateCard icon={AlertTriangle} title="Reports do not match" meaning="Payment is disputed; Work is unchanged." next="Open shared facts" tone="coral" /><StateCard icon={ShieldCheck} title="Manual review" meaning="Automation cannot decide safely." next="Operations reviews context" tone="mango" /></div></section>

      <section className="mt-10"><SectionHeading eyebrow="04 · Complex product pattern" title="Work × payment separation" /><Card className="overflow-hidden"><div className="grid lg:grid-cols-3"><Aggregate title="Order" state="Accepted" detail="Snapshot v1 · ₱80 · both parties" tone="forest" icon={LockKeyhole} /><Aggregate title="Work" state="In progress" detail="Maya owns First draft" tone="mango" icon={Sparkles} /><Aggregate title="Payment obligation" state="Buyer report missing" detail="External Cash · Serbizyu holds ₱0" tone="blue" icon={Banknote} /></div><div className="border-t border-ink-100 bg-cream-50 px-5 py-4 text-xs leading-5 text-ink-500"><strong className="text-ink-800">Design rule:</strong> no combined “Paid / Done” badge. Each state explains meaning, responsible actor, consequence, and recovery.</div></Card></section>

      <section className="mt-10 grid gap-6 xl:grid-cols-2">
        <div><SectionHeading eyebrow="05 · Edge pattern" title="Air-gapped QR transfer" /><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-ink-100 px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-violet-50 text-violet-700"><QrCode className="h-5 w-5" /></span><div><h3 className="font-display text-sm font-extrabold text-ink-950">Signed packet relay</h3><p className="text-[10px] text-ink-400">Exploratory · fixture only</p></div></div><button className={cn("rounded-full px-3 py-1.5 text-[10px] font-extrabold", offline ? "bg-coral-50 text-coral-600" : "bg-forest-50 text-forest-700")} onClick={() => setOffline(!offline)}>{offline ? "Offline" : "Live feed"}</button></div><div className="grid gap-5 p-5 sm:grid-cols-[190px_1fr]"><div className="relative grid aspect-square place-items-center overflow-hidden rounded-3xl bg-ink-950 p-6 text-white pattern-grid"><ScanLine className="absolute h-[72%] w-[72%] text-forest-300/30" /><div className="relative grid grid-cols-6 gap-1">{Array.from({ length: 36 }).map((_, index) => <span key={index} className={cn("h-3 w-3 rounded-[2px]", ((index * 7 + frame * 3) % 5) < 2 ? "bg-white" : "bg-forest-400/30")} />)}</div><span className="absolute bottom-3 text-[9px] font-bold text-white/50">FRAME {frame}/6 · CRC OK</span></div><div><div className="flex items-center gap-2"><Radio className={cn("h-4 w-4", offline ? "text-coral-500" : "animate-pulse text-forest-500")} /><strong className="text-sm text-ink-900">{offline ? "Feed paused — frames kept" : "Receiving signed frames"}</strong></div><p className="mt-2 text-xs leading-5 text-ink-500">No payment or release is authorized by QR alone. The receiver verifies packet identity, freshness, sequence, signature, and explicit user confirmation.</p><div className="mt-4 flex gap-2"><Button size="sm" disabled={offline} onClick={() => setFrame((value) => value === 6 ? 1 : value + 1)} leftIcon={<ScanLine className="h-3.5 w-3.5" />}>Next frame</Button><Button size="sm" variant="outline" leftIcon={<Copy className="h-3.5 w-3.5" />}>Copy packet ID</Button></div><div className="mt-4 rounded-xl bg-ink-50 p-3 text-[10px] leading-4 text-ink-500"><strong className="text-ink-800">Failure states:</strong> stale · missing frame · signature mismatch · revoked · duplicate · user denied.</div></div></div></Card></div>

        <div><SectionHeading eyebrow="06 · Formulation pattern" title="Archetype composer" /><Card className="p-5"><p className="text-xs leading-5 text-ink-500">Compose a Work shape and payment lane without creating an invalid Order. Incompatible choices are visibly blocked, never silently corrected.</p><div className="mt-5 grid grid-cols-2 gap-2">{archetypes.map(({ id, title, icon: Icon }) => <button key={id} className={cn("flex min-h-16 items-center gap-3 rounded-2xl border p-3 text-left transition", shape === id ? "border-forest-400 bg-forest-50 ring-2 ring-forest-100" : "border-ink-100 bg-white hover:border-ink-200")} onClick={() => setShape(id)}><span className={cn("grid h-9 w-9 shrink-0 place-items-center rounded-xl", shape === id ? "bg-forest-600 text-white" : "bg-ink-50 text-ink-500")}><Icon className="h-4 w-4" /></span><span><strong className="block text-xs text-ink-900">{id}</strong><small className="block text-[10px] text-ink-400">{title}</small></span></button>)}</div><div className="mt-5"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-ink-400">Payment lane</p><div className="mt-2 space-y-2">{lanes.map((item) => { const enabled = currentShape.compatible.includes(item.id); return <button key={item.id} className={cn("flex w-full items-center justify-between rounded-xl border px-3 py-3 text-left transition", lane === item.id ? "border-forest-400 bg-forest-50" : "border-ink-100 bg-white", !enabled && "cursor-not-allowed opacity-45")} disabled={!enabled} onClick={() => setLane(item.id)}><span><strong className="block text-xs text-ink-900">{item.title}</strong><small className="text-[10px] text-ink-400">{enabled ? item.label : `Not compatible with ${shape}`}</small></span>{item.sandbox ? <Badge tone="sandbox">Sandbox</Badge> : lane === item.id ? <Check className="h-4 w-4 text-forest-600" /> : <ChevronRight className="h-4 w-4 text-ink-300" />}</button>; })}</div></div><div className={cn("mt-5 rounded-2xl border p-4", compatible ? "border-forest-200 bg-forest-50" : "border-coral-200 bg-coral-50")}><div className="flex items-center justify-between"><strong className="text-xs text-ink-900">Contract snapshot</strong><Badge tone={compatible ? "forest" : "coral"}>{compatible ? "Compatible" : "Blocked"}</Badge></div><pre className="mt-3 overflow-x-auto text-[10px] leading-5 text-ink-600">{JSON.stringify(snapshot, null, 2)}</pre></div></Card></div>
      </section>
    </main>
  );
}

function ColorSwatch({ color, name, role, hex, dark }: { color: string; name: string; role: string; hex: string; dark?: boolean }) { return <div><div className={cn("h-20 rounded-2xl border border-black/5 p-3", color)}><span className={cn("font-mono text-[9px] font-bold", dark ? "text-ink-500" : "text-white/75")}>{hex}</span></div><strong className="mt-2 block text-xs text-ink-900">{name}</strong><small className="text-[10px] text-ink-400">{role}</small></div>; }
function StateCard({ icon: Icon, title, meaning, next, tone }: { icon: typeof AlertTriangle; title: string; meaning: string; next: string; tone: "blue" | "neutral" | "coral" | "mango" }) { const styles = { blue: "bg-blue-50 text-blue-700", neutral: "bg-ink-100 text-ink-600", coral: "bg-coral-50 text-coral-600", mango: "bg-mango-50 text-mango-700" }; return <Card className="p-5"><span className={cn("grid h-10 w-10 place-items-center rounded-2xl", styles[tone])}><Icon className="h-5 w-5" /></span><h3 className="mt-4 text-sm font-extrabold text-ink-950">{title}</h3><p className="mt-2 text-xs leading-5 text-ink-500">{meaning}</p><p className="mt-4 border-t border-ink-100 pt-3 text-[10px] font-bold text-forest-700">Next: {next}</p></Card>; }
function Aggregate({ title, state, detail, tone, icon: Icon }: { title: string; state: string; detail: string; tone: "forest" | "mango" | "blue"; icon: typeof Banknote }) { const styles = { forest: "bg-forest-50 text-forest-700", mango: "bg-mango-50 text-mango-700", blue: "bg-blue-50 text-blue-700" }; return <div className="border-b border-ink-100 p-5 last:border-0 lg:border-b-0 lg:border-r"><span className={cn("grid h-10 w-10 place-items-center rounded-2xl", styles[tone])}><Icon className="h-5 w-5" /></span><p className="mt-4 text-[10px] font-extrabold uppercase tracking-[.12em] text-ink-400">{title}</p><strong className="mt-1 block text-base text-ink-950">{state}</strong><p className="mt-1 text-[11px] leading-4 text-ink-500">{detail}</p></div>; }
