import { currentUser, openRequests, primaryOrder, serviceListings, workPlan } from "@/data/fixtures";
import type { AgentGrant, AgentTask, QuickDealOffer } from "@/types/domain";
import type { ScenarioEvent, ScenarioSnapshot } from "@/application/gateway";
const storageKey = "serbizyu:scenario:v1";
const quickDeal: QuickDealOffer = { id: "QD-DEMO-01", listingId: "SRV-102", listingTitle: "Pick up medicine or small items", seller: serviceListings[1].provider, buyer: currentUser, listedAmount: 70, amount: 70, status: "ready", round: 0, frame: 1 };
const agentGrants: AgentGrant[] = [{ id: "GRANT-LOLA-01", ownerId: "USR-LOLA-01", ownerName: "Lola Nena", scope: ["manage listing drafts", "coordinate requests"], status: "active", expiresLabel: "No expiry set in demo" }];
const agentTasks: AgentTask[] = [{ id: "AGT-TASK-01", title: "Review Lola Nena’s seedling request", ownerId: "USR-LOLA-01", ownerName: "Lola Nena", urgency: "now", status: "needs_action", nextAction: "Open the request and prepare a draft response", requiresApproval: true, relatedRoute: "/explore" }, { id: "AGT-TASK-02", title: "Check invitation order update", ownerId: "USR-LOLA-01", ownerName: "Lola Nena", urgency: "today", status: "waiting_owner", nextAction: "Wait for Owner approval before sending", requiresApproval: true, relatedRoute: "/orders/ORD-260801-08" }, { id: "AGT-TASK-03", title: "Cash handoff decision", ownerId: "USR-LOLA-01", ownerName: "Lola Nena", urgency: "waiting", status: "blocked", nextAction: "Do not hold or report cash for the Owner", requiresApproval: true }];
function seed(): ScenarioSnapshot { return { schemaVersion: 1, scenarioId: "SCN-01", fixtureClass: "fictional_demo", reviewerActorId: currentUser.id, viewer: structuredClone(currentUser), agentGrants: structuredClone(agentGrants), agentTasks: structuredClone(agentTasks), services: structuredClone(serviceListings), requests: structuredClone(openRequests), order: structuredClone(primaryOrder), plan: structuredClone(workPlan), quickDeal: structuredClone(quickDeal), events: [], versions: { [primaryOrder.id]: 1, [quickDeal.id]: 1 } }; }
let memory: ScenarioSnapshot | null = null;
function readStorage(): ScenarioSnapshot | null { if (typeof window === "undefined") return null; const raw = window.localStorage.getItem(storageKey); if (!raw) return null; try { const parsed = JSON.parse(raw) as Partial<ScenarioSnapshot>; const base = seed(); return { ...base, ...parsed, schemaVersion: 1, agentGrants: parsed.agentGrants ?? base.agentGrants, agentTasks: parsed.agentTasks ?? base.agentTasks, events: parsed.events ?? [], versions: parsed.versions ?? base.versions }; } catch { return null; } }
function persist(value: ScenarioSnapshot) { memory = value; if (typeof window !== "undefined") { window.localStorage.setItem(storageKey, JSON.stringify(value)); window.dispatchEvent(new Event("serbizyu:scenario-changed")); } }
export function getScenario(): ScenarioSnapshot { if (!memory) { memory = readStorage() ?? seed(); persist(memory); } return structuredClone(memory); }
export function resetScenario(): ScenarioSnapshot { const value = seed(); persist(value); return structuredClone(value); }
export function updateScenario(mutator: (draft: ScenarioSnapshot) => ScenarioEvent | undefined): ScenarioSnapshot { const draft = getScenario(); const event = mutator(draft); if (event) draft.events = [...draft.events, event]; persist(draft); return structuredClone(draft); }
export function setReviewerActor(actorId: string): ScenarioSnapshot { return updateScenario((draft) => { draft.reviewerActorId = actorId; return { id: `EV-${Date.now()}`, type: "reviewer.actor_changed", aggregateType: "Scenario", aggregateId: draft.scenarioId, actorId, at: new Date().toISOString(), note: `Reviewer perspective changed to ${actorId}.` }; }); }
export function updateViewerProfile(input: { name: string; area: string }): ScenarioSnapshot { return updateScenario((draft) => { draft.viewer = { ...draft.viewer, name: input.name.trim() || draft.viewer.name, shortName: (input.name.trim() || draft.viewer.name).split(" ")[0], area: input.area.trim() || draft.viewer.area }; return { id: `EV-${Date.now()}`, type: "account.profile_updated", aggregateType: "ViewerAccount", aggregateId: draft.viewer.id, actorId: draft.viewer.id, at: new Date().toISOString(), note: "Profile changed in the fictional local scenario." }; }); }
export function scenarioStorageKey() { return storageKey; }
